name: Windows Build

on:
  push:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    env:
      OPENAI_APIKEY: ${{ secrets.OPENAI_APIKEY }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'  # or 6.0.x as needed

      - name: Restore solution
        run: dotnet restore ./Clocktower/Clocktower.sln

      - name: Build solution
        run: dotnet build ./Clocktower/Clocktower.sln --configuration Release

      # Publish the Clocktower WPF/WinForms (self-contained exe)
      - name: Publish Clocktower
        run: dotnet publish ./Clocktower/Clocktower/Clocktower.csproj --configuration Release --runtime win-x64 --self-contained true
          
      # Upload artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-builds
          # You can include multiple paths by separating them with newlines
          path: |
            Clocktower/Clocktower/bin/Release/net7.0-windows/win-x64/publish
            Clocktower/ChatApplication/ChatApplication/bin/Release/net7.0-windows/win-x64/publish
            Clocktower/DiscordChatBot/DiscordChatBot/bin/Release/net7.0-windows/win-x64/publish
