name: Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      # 1. Check out your repository code
      - name: Checkout
        uses: actions/checkout@v2

      # 2. Set up .NET (change '7.0.x' if your project targets another version)
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      # 3. Restore NuGet packages for the whole solution
      - name: Restore
        run: dotnet restore ./Clocktower.sln

      # 4. Build the solution in Release mode
      - name: Build
        run: dotnet build ./Clocktower.sln --configuration Release

      # 5. Publish the 'Clocktower' WPF project as a self-contained Windows exe
      #    (If you also want to publish ChatApplication, you can repeat this step.)
      - name: Publish Clocktower
        run: dotnet publish ./Clocktower/Clocktower.csproj \
          --configuration Release \
          --runtime win-x64 \
          --self-contained true

      # 6. Upload the published files as an artifact you can download
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: published-build
          # Update the path if your publish folder has a different name/framework
          path: ./Clocktower/Clocktower/bin/Release/net7.0-windows/win-x64/publish
